# fly.toml app configuration file generated for app-misty-river-4518 on 2024-10-11T21:06:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-misty-river-4518'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'mssql'
  destination = '/var/opt/mssql'

[http_service]
  internal_port = 1433
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
